services:
  - type: web
    name: supply-control-api
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./backend/Dockerfile
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    autoDeploy: true
    envVars:
      - key: ENV_FILE_PATH
        value: /app/.env